# Generated by Django 3.1.7 on 2021-03-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutterpit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='pic',
            new_name='picture',
        ),
    ]
