# Generated by Django 3.1.7 on 2021-03-22 07:37

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterpit', '0002_auto_20210322_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
