# Generated by Django 3.1.7 on 2021-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutterpit', '0003_auto_20210322_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pic',
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
